name: olympic-workspace

services:

  workspace:
    build:
      context: ./.workspace

    container_name: olympic-workspace

    hostname: olympic-workspace

    restart: unless-stopped

    working_dir: /workspace

    ports:
      - "127.0.0.1:2222:22"
      - "127.0.0.1:4200:4200"

    volumes:

      # Code uniquement
      - .:/workspace

      # node_modules reste exclusivement dans Docker
      - olympic-node-modules:/workspace/node_modules

      # VS Code Server + extensions distantes persistants
      - olympic-vscode-server:/home/node/.vscode-server

      # fingerprint SSH stable
      - olympic-ssh-host-keys:/var/lib/ssh-host-keys

      # clé PUBLIQUE uniquement
      - ./.workspace/authorized_keys:/tmp/authorized_keys:ro

    networks:
      - olympic-dev

volumes:

  olympic-node-modules:
    name: olympic-node-modules

  olympic-vscode-server:
    name: olympic-vscode-server

  olympic-ssh-host-keys:
    name: olympic-ssh-host-keys

networks:

  olympic-dev:
    name: olympic-dev
